general {
    col.active_border = rgba(408A8Eff) rgba(CCFCFFff) 45deg
    col.inactive_border = rgba(E0D5ADff) rgba(D9765Fff) 45deg
}

group {
    col.border_active = rgba(408A8Eff) rgba(CCFCFFff) 45deg
    col.border_inactive = rgba(E0D5ADcc) rgba(D9765Fcc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(090909cc) rgba(0F1011cc) 45deg
}
