general {
    col.active_border = rgba(EDD3BAff) rgba(523D29ff) 45deg
    col.inactive_border = rgba(101B23ff) rgba(464C53ff) 45deg
}

group {
    col.border_active = rgba(EDD3BAff) rgba(523D29ff) 45deg
    col.border_inactive = rgba(101B23cc) rgba(464C53cc) 45deg
    col.border_locked_active = rgba(111212ff) rgba(070707ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
