general {
    col.active_border = rgba(B6B4D7ff) rgba(2B2952ff) 45deg
    col.inactive_border = rgba(201D21ff) rgba(423F51ff) 45deg
}

group {
    col.border_active = rgba(B6B4D7ff) rgba(2B2952ff) 45deg
    col.border_inactive = rgba(201D21cc) rgba(423F51cc) 45deg
    col.border_locked_active = rgba(EDEDEDff) rgba(090909ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
